
var ClassClient = function(){


    // Little Helper
    if (!location.origin)
       location.origin = location.protocol + "//" + location.host;

    /* Start of Config*/

    // Use current url, but should be hardcoded in production to something like:
    // 'https://dev.sanso.pw' or 'http://dev.sanso.pw:8001'
    // Please only use http instead of https for development purposes only and NEVER in production!
    var backend = location.origin;

    /* End of Config */

    /**
     * takes the sha512 of lowercase email as salt to generate scrypt password hash in hex called the authkey
     *
     * For compatibility reasons with other clients please use the following parameters if you create your own client:
     *
     * var n = 16384;
     * var r = 8;
     * var p = 1;
     * var l = 64;
     *
     * @param {string} email - email address of the user
     * @param {string} password - password of the user
     * @returns auth_key - scrypt hex value of the password with the sha512 of lowercase email as salt
     */
    this.generate_authkey = function (email, password) {

        var n = 16384;
        var r = 8;
        var p = 1;
        var l = 64; // 64 Bytes = 512 Bits

        var scrypt = scrypt_module_factory();

        // takes the email address basically as salt. sha512 is used to enforce minimum length
        var salt = CryptoJS.SHA512(email.toLowerCase());

        return scrypt.to_hex(scrypt.crypto_scrypt(scrypt.encode_utf8(password), scrypt.encode_utf8(salt), n, r, p, l));
    };

    /**
     * Ajax POST request to the backend with the email and authkey, returns nothing but an email is sent to the user
     * with an activation_code for the email
     *
     * @param {string} email - email address of the user
     * @param {string} authkey - authkey gets generated by generate_authkey(email, password)
     * @returns {*}
     */
    this.authentication_register = function(email, authkey) {
        var endpoint = '/authentication/register/';
        var type = "POST";
        var data = {
            email: email,
            authkey: authkey
        };

        return $.ajax({
            type: type,
            url: backend+endpoint,
            data: data,
            dataType: 'text' // will be json but for demonstration purposes we insist on text
        });
    };

    /**
     * Ajax POST request to the backend with the activation_code for the email, returns nothing. If successful the user
     * can login afterwards
     *
     * @param activation_code
     * @returns {*}
     */
    this.authentication_verify_email = function(activation_code) {
        var endpoint = '/authentication/verify-email/';
        var type = "POST";
        var data = {
            activation_code: activation_code
        };

        return $.ajax({
            type: type,
            url: backend+endpoint,
            data: data,
            dataType: 'text' // will be json but for demonstration purposes we insist on text
        });
    };
    /**
     * Ajax POST request to the backend with email and authkey for login, returns the token for further authentication
     *
     * @param {string} email - email address of the user
     * @param {string} authkey - authkey gets generated by generate_authkey(email, password)
     * @returns {*}
     */
    this.authentication_login = function(email, authkey) {
        var endpoint = '/authentication/login/';
        var type = "POST";
        var data = {
            email: email,
            authkey: authkey
        };

        return $.ajax({
            type: type,
            url: backend+endpoint,
            data: data,
            dataType: 'text' // will be json but for demonstration purposes we insist on text
        });
    };

    /**
     * Ajax GET request with the token as authentication to get the current user's datastore
     *
     * @param {string} token - authentication token of the user, returned by authentication_login(email, authkey)
     * @param {uuid} [datastore_id=null] - the datastore ID
     * @returns {*}
     */
    this.read_datastore = function(token, datastore_id) {

        //optional parameter datastore_id
        if (typeof datastore_id === 'undefined') { datastore_id = null; }

        var endpoint = '/datastore/' + (datastore_id == null ? '' : datastore_id+'/');
        var type = "GET";

        return $.ajax({
            type: type,
            url: backend+endpoint,
            data: null, // No data required for get
            dataType: 'text', // will be json but for demonstration purposes we insist on text
            beforeSend: function( xhr ) {
                xhr.setRequestHeader ("Authorization", "Token "+token);
            }
        });
    };

    /**
     * Ajax PUT request with the token as authentication and the new datastore content
     *
     * @param {string} token - authentication token of the user, returned by authentication_login(email, authkey)
     * @param {uuid} datastore_id - the datastore ID
     * @param {string} datastore - AES and Base64 encoded data
     * @returns {*}
     */
    this.write_datastore = function(token, datastore_id, datastore) {
        var endpoint = '/datastore/'+datastore_id+'/';
        var type = "POST";
        var data = {
            data: datastore
        };

        return $.ajax({
            type: type,
            url: backend+endpoint,
            data: data,
            dataType: 'text', // will be json but for demonstration purposes we insist on text
            beforeSend: function( xhr ) {
                xhr.setRequestHeader ("Authorization", "Token "+token);
            }
        });
    }
};


