from .activate_token import ActivateTokenView
from .datastore import DatastoreView
from .ga_verify import GAVerifyView
from .duo_verify import DuoVerifyView
from .group import GroupView
from .membership_accept import MembershipAcceptView
from .membership_decline import MembershipDeclineView
from .membership import MembershipView
from .health_check import HealthCheckView
from .info import InfoView
from .status import StatusView
from .login import LoginView
from .logout import LogoutView
from .password import PasswordView
from .recoverycode import RecoveryCodeView
from .register import RegisterView
from .secret import SecretView
from .secret_link import SecretLinkView
from .session import SessionView
from .share import ShareView
from .share_right import ShareRightView
from .share_right_accept import ShareRightAcceptView
from .share_right_decline import ShareRightDeclineView
from .share_rights import ShareRightsView
from .share_link import ShareLinkView
from .user_ga import UserGA
from .user_duo import UserDuo
from .user_search import UserSearch
from .user_update import UserUpdate
from .user_yubikey_otp import UserYubikeyOTP
from .user_delete import UserDelete
from .verify_email import VerifyEmailView
from .yubikey_otp_verify import YubikeyOTPVerifyView
from .group_rights import GroupRightsView