# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
from typing import List, Tuple


class Migration(migrations.Migration):

    initial = True

    dependencies = [] # type: List[Tuple]

    operations = [
        migrations.RunSQL("""CREATE EXTENSION IF NOT EXISTS "pgcrypto";"""),
        migrations.RunSQL("""CREATE EXTENSION IF NOT EXISTS ltree;"""),
        #migrations.RunSQL("CREATE INDEX IF NOT EXISTS restapi_share_tree_path_6dcc1339 ON restapi_share_tree USING GIST(path);"),
    ]
