# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20170502_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='client_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='write_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
