# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20170625_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_store',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Designates whether this is the default datastore for this type or not', verbose_name='default'),
        ),
    ]
