# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_data_store_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='valid_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
