# Generated by Django 2.0 on 2018-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20180114_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='duo',
            name='active',
            field=models.BooleanField(default=True, help_text='Designates whether this 2FA is active or not.', verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='google_authenticator',
            name='active',
            field=models.BooleanField(default=True, help_text='Designates whether this 2FA is active or not.', verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='yubikey_otp',
            name='active',
            field=models.BooleanField(default=True, help_text='Designates whether this 2FA is active or not.', verbose_name='Is Active?'),
        ),
    ]
