# Generated by Django 2.0.2 on 2018-03-08 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_auto_20180222_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('authkey', models.CharField(max_length=128, null=True, verbose_name='auth key')),
                ('public_key', models.CharField(max_length=256, verbose_name='public key')),
                ('private_key', models.CharField(max_length=256, verbose_name='private key')),
                ('private_key_nonce', models.CharField(max_length=64, unique=True, verbose_name='private key nonce')),
                ('secret_key', models.CharField(max_length=256, verbose_name='secret key')),
                ('secret_key_nonce', models.CharField(max_length=64, unique=True, verbose_name='secret key nonce')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Old_Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=512, unique=True, verbose_name='email address')),
                ('email_bcrypt', models.CharField(max_length=60, unique=True, verbose_name='bcrypt of email address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='authentication',
            field=models.CharField(default='AUTHKEY', max_length=16, verbose_name='Authentication method'),
        ),
        migrations.AddField(
            model_name='old_email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_emails', to='restapi.User'),
        ),
        migrations.AddField(
            model_name='old_credential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_credentials', to='restapi.User'),
        ),
    ]
