# Generated by Django 2.1.4 on 2018-12-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0020_auto_20180628_0537'),
        ('restapi', '0022_auto_20181207_1954'),
    ]

    operations = [
    ]
