# Generated by Django 2.1.3 on 2018-12-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_auto_20181207_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='restapi.API_Key'),
        ),
    ]
