# Generated by Django 2.1.3 on 2018-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0023_token_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='read',
            field=models.BooleanField(default=True, help_text='Read permissions', verbose_name='Read'),
        ),
        migrations.AddField(
            model_name='token',
            name='write',
            field=models.BooleanField(default=True, help_text='Write permissions', verbose_name='Write'),
        ),
    ]
