# Generated by Django 2.1.4 on 2018-12-30 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0023_merge_20181230_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('link_id', models.UUIDField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='secret',
        ),
        migrations.AddField(
            model_name='file',
            name='size_uploaded',
            field=models.BigIntegerField(default=0, help_text='The amount of bytes (including encryption overhead) already uploaded', verbose_name='Size Uploaded'),
        ),
        migrations.AlterField(
            model_name='data_store',
            name='type',
            field=models.CharField(db_index=True, default='password', max_length=64),
        ),
        migrations.AlterField(
            model_name='fileserver_cluster_members',
            name='key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='fileserver_cluster_members',
            name='valid_till',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='secret',
            name='type',
            field=models.CharField(db_index=True, default='password', max_length=64),
        ),
        migrations.AlterField(
            model_name='secret_link',
            name='secret',
            field=models.ForeignKey(help_text='The secret, that this link links to.', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='restapi.Secret'),
        ),
        migrations.AddField(
            model_name='file_link',
            name='file',
            field=models.ForeignKey(help_text='The file, that this link links to.', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='restapi.File'),
        ),
        migrations.AddField(
            model_name='file_link',
            name='parent_datastore',
            field=models.ForeignKey(help_text='The datastore, where this link ends', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='restapi.Data_Store'),
        ),
        migrations.AddField(
            model_name='file_link',
            name='parent_share',
            field=models.ForeignKey(help_text='The share, where this link ends and gets its permissions from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='restapi.Share'),
        ),
        migrations.AddField(
            model_name='file',
            name='chunk_count_uploaded',
            field=models.IntegerField(default=0, help_text='The amount of chunks already uploaded', verbose_name='Chunks Uploaded'),
        ),
    ]
