# Generated by Django 2.1.4 on 2018-12-24 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0023_merge_20181224_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size_uploaded',
            field=models.BigIntegerField(default=0, help_text='The amount of bytes (including encryption overhead) already uploaded', verbose_name='Size Uploaded'),
        ),
        migrations.AlterField(
            model_name='data_store',
            name='type',
            field=models.CharField(db_index=True, default='password', max_length=64),
        ),
        migrations.AlterField(
            model_name='fileserver_cluster_members',
            name='key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='type',
            field=models.CharField(db_index=True, default='password', max_length=64),
        ),
        migrations.AlterField(
            model_name='fileserver_cluster_members',
            name='valid_till',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
