# Generated by Django 2.1.7 on 2019-03-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0024_auto_20190127_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileserver_cluster_member_shard_link',
            old_name='delete',
            new_name='delete_capability',
        ),
        migrations.RenameField(
            model_name='fileserver_cluster_members',
            old_name='delete',
            new_name='delete_capability',
        ),
        migrations.RenameField(
            model_name='fileserver_cluster_shard_link',
            old_name='delete',
            new_name='delete_capability',
        ),
    ]
