# Generated by Django 3.2.15 on 2023-01-30 09:54

from django.db import migrations, models
import django.utils.timezone


def legacy_hashing_parameters():
    # Existing credentials were derived with this profile. Keep it frozen here,
    # independently of the defaults used to create new credentials.
    return {"u": 14, "r": 8, "p": 1, "l": 64}


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0031_auto_20221005_1928"),
    ]

    operations = [
        migrations.AddField(
            model_name="old_credential",
            name="hashing_algorithm",
            field=models.CharField(
                choices=[("scrypt", "scrypt")],
                default="scrypt",
                max_length=32,
                verbose_name="hashing algorithm",
            ),
        ),
        migrations.AddField(
            model_name="old_credential",
            name="hashing_parameters",
            field=models.JSONField(
                default=legacy_hashing_parameters,
                verbose_name="hashing parameters",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                default="", max_length=512, verbose_name="display name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hashing_algorithm",
            field=models.CharField(
                choices=[("scrypt", "scrypt")],
                default="scrypt",
                max_length=32,
                verbose_name="hashing algorithm",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hashing_parameters",
            field=models.JSONField(
                default=legacy_hashing_parameters,
                verbose_name="hashing parameters",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
