# Generated by Django 4.2.10 on 2024-02-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0033_group_file_repository_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(db_index=True, max_length=64, null=True, verbose_name='external id'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=16, verbose_name='language'),
        ),
    ]
