# Generated by Django 4.2.11 on 2024-04-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0035_secret_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='forced_membership',
            field=models.BooleanField(default=False, help_text='Designates whether users can deny or leave this groups membership', verbose_name='Forced Membership'),
        ),
    ]
