# Generated by Django 3.2.20 on 2024-06-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0034_auto_20240304_1306'),
        ('restapi', '0037_avatar'),
    ]

    operations = [
    ]
