# Generated by Django 3.2.20 on 2024-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0038_merge_0034_auto_20240304_1306_0037_avatar'),
    ]

    operations = [
         migrations.AddField(
            model_name='token',
            name='ivalt_2fa',
            field=models.BooleanField(default=False, help_text='iValt 2fa',
                                      verbose_name='iValt 2FA'),
        ),
    ]
