# Generated by Django 4.2.20 on 2025-04-16 10:20

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0039_link_share_allow_write_alter_ivalt_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zoneinfo',
            field=timezone_field.fields.TimeZoneField(null=True),
        ),
    ]
