# Generated by Django 4.2.20 on 2025-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0041_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='session_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
