# Generated by Django 4.2.21 on 2025-11-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0045_device_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='secret',
            field=models.ForeignKey(blank=True, help_text='The secret this file is attached to (if it is an attachment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_files', to='restapi.secret'),
        ),
    ]
